# Generated by Django 2.1.7 on 2019-02-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('number_of_installments', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='total_price_per_product',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='emidetails',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=240),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.Customer'),
        ),
        migrations.AddField(
            model_name='emidetails',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allapps.Order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allapps.Order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allapps.Order'),
        ),
    ]
