# Generated by Django 2.1.7 on 2019-02-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0002_auto_20190223_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_installments',
        ),
        migrations.AddField(
            model_name='emidetails',
            name='number_of_installments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allapps.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.Customer'),
        ),
    ]
