# Generated by Django 2.1.7 on 2019-02-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0003_auto_20190223_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('pincode_class', models.IntegerField()),
            ],
        ),
    ]
