# Generated by Django 2.1.7 on 2019-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0005_auto_20190224_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
