# Generated by Django 2.1.7 on 2019-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0006_auto_20190224_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mobile_wallet_used',
            field=models.CharField(max_length=30),
        ),
    ]
